version: "3.9"
services:
  chat-jco:
    build:
      context: .
      dockerfile:
        Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/Bases--NodeJs:delegated
  db:
    image: mongo:6-alpine
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jesus
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
  # LOS DATOS DE LA BD
