version: "3.9"
services:
  chat-jco:
    build: .
    ports: 
      - "3000:3000"
    links:
      - db
  db:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data: